# This is a basic workflow to help you get started with Actions

language: c
dist: ubuntu-latest
compiler: gcc
sudo: required
install:
    - sudo apt-get update

     #Install cmake
    - sudo apt install -y cmake

     #Install valgrind
    - sudo apt-get install -y valgrind
script:
    - mkdir build
    - cd build
    - cmake ../
    - make